postgresql: &postgresql
  adapter: postgresql
  database: br_painel
  username: waze
  password: waze
  host:     localhost
  port:     5432
  min_messages: ERROR
  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "postgresql" %>

development:
  adapter: postgresql
  database: br_painel
  username: waze
  password: waze
  host:     127.0.0.1
  port:     5432
  min_messages: ERROR
  reconnect: false
  pool: 5
  timeout: 5000
  encoding: utf8

test: &test
  <<: *defaults

production:
  <<: *defaults
